CFLAGS += -Werror

all:
	make -C tr69_lib
	make -C tr69_build
	make -C tr69_core
	make -C tr69_func
clean:
	make -C tr69_lib clean
	make -C tr69_build clean
	make -C tr69_core clean
	make -C tr69_func clean
