#ifndef LIBTR69_IMP_H
#define LIBTR69_IMP_H

#define TR69_FUNC_GET_LEAF_DATA         1
#define TR69_FUNC_GET_UNFRESH_LEAF_DATA 2
#define TR69_FUNC_SET_LEAF_DATA         3
#define TR69_FUNC_ACL_SET_LEAF_DATA     4
#define TR69_FUNC_GET_NODE              5
#define TR69_FUNC_GET_NEXT_NODE         6
#define TR69_FUNC_SET_NODE              7
#define TR69_FUNC_ADD_INSTANCE          8
#define TR69_FUNC_DEL_INSTANCE          9
#define TR69_FUNC_DEL2_INSTANCE         10
#define TR69_FUNC_GET_NOTIFICATION      11
#define TR69_FUNC_SET_UNFRESH_LEAF_DATA 12
#define TR69_FUNC_SAVE_NOW              13

#define TR69_FUNC_COMMIT_BEGIN          14
#define TR69_FUNC_COMMIT_SET_LEAF_DATA  15
#define TR69_FUNC_COMMIT_END            16

#define TR69_FUNC_RESTORE_DEFUALT_NODE  17
#define TR69_FUNC_GET_NEXT_OBJ_NODE     18

#define TR69_FUNC_GET_NEXT_NODE2		19
#define TR69_FUNC_GET_NEXT_INST_NODE	20
#define TR69_FUNC_GET_NEXT_CHILD_NODE	21
#define TR69_FUNC_GET_SAME_DEPTH_NODE	22
#define TR69_FUNC_GET_OBJ_DATA_SIZE		23
#define TR69_FUNC_MOVE_INSTANCE 		24
#define TR69_FUNC_CLEAR_NOTIFICATION 25

//#define TR69_SOCK_PORT

#define TR69_SERVER_FILE "/var/sock_tr69_data_server"
#define TR69_SERVER_IP   "127.0.0.1"
#define TR69_SERVER_PORT 1343

#endif
